export const boards = [
    {
      id: 1,
      title: 'Welcome Board',
      category: 'inspiration',
      image: 'https://picsum.photos/200/300',
    },
    {
      id: 2,
      title: 'Celebration Highlights',
      category: 'celebration',
      image: 'https://picsum.photos/200/300',
    },
    {
      id: 3,
      title: 'Thank You Notes',
      category: 'thank you',
      image: 'https://picsum.photos/200/300',
    },
    {
      id: 4,
      title: 'Motivational Quotes',
      category: 'inspiration',
      image: 'https://picsum.photos/200/300',
    },
    {
      id: 5,
      title: 'Team Achievements',
      category: 'celebration',
      image: 'https://picsum.photos/200/300',
    },
    {
      id: 6,
      title: 'Appreciation Board',
      category: 'thank you',
      image: 'https://picsum.photos/200/300',
    },
    {
      id: 7,
      title: 'Inspiration Wall',
      category: 'inspiration',
      image: 'https://picsum.photos/200/300',
    },
    {
      id: 8,
      title: 'Milestone Moments',
      category: 'celebration',
      image: 'https://picsum.photos/200/300',
    },
  ]


  export const cards = [
    {
      id: 101,
      boardId: 1,
      title: 'Great Start!',
      message: 'Kudos for getting the project off the ground!',
      gif: 'https://media.giphy.com/media/3oEjI6SIIHBdRxXI40/giphy.gif',
      upvotes: 5,
      author: 'Alice',
    },
    {
      id: 102,
      boardId: 1,
      title: 'Keep it up!',
      message: 'Loving the momentum here!',
      gif: 'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif',
      upvotes: 3,
      author: 'Bob',
    },
    {
      id: 103,
      boardId: 1,
      title: 'Fantastic Effort!',
      message: 'Your dedication really shows!',
      gif: 'https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy.gif',
      upvotes: 4,
      author: 'Clara',
    },
    {
      id: 201,
      boardId: 2,
      title: 'Congrats on Launch!',
      message: 'Celebrating the successful new product launch.',
      gif: 'https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif',
      upvotes: 10,
      author: 'Charlie',
    },
    {
      id: 202,
      boardId: 2,
      title: 'Way to go team!',
      message: 'Teamwork made the dream work!',
      gif: 'https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif',
      upvotes: 8,
      author: 'Dana',
    },
    {
      id: 203,
      boardId: 2,
      title: 'Victory Dance',
      message: 'We did it! Time to celebrate!',
      gif: 'https://media.giphy.com/media/111ebonMs90YLu/giphy.gif',
      upvotes: 9,
      author: 'Ethan',
    },
    {
      id: 301,
      boardId: 3,
      title: 'Thanks a ton!',
      message: 'Appreciate all your help on the support desk.',
      gif: 'https://media.giphy.com/media/xUPGcguWZHRC2HyBRS/giphy.gif',
      upvotes: 7,
      author: 'Eve',
    },
    {
      id: 302,
      boardId: 3,
      title: 'Much appreciated!',
      message: 'Your hard work never goes unnoticed.',
      gif: 'https://media.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/giphy.gif',
      upvotes: 4,
      author: 'Frank',
    },
    {
      id: 303,
      boardId: 3,
      title: 'Super Supportive',
      message: 'Thanks for always being there to help.',
      gif: 'https://media.giphy.com/media/l41lFw057lAJQMwg0/giphy.gif',
      upvotes: 6,
      author: 'Grace',
    },
    {
      id: 401,
      boardId: 4,
      title: 'Motivation Monday',
      message: 'Starting the week with positive vibes!',
      gif: 'https://media.giphy.com/media/3o6ZtaO9BZHcOjmErm/giphy.gif',
      upvotes: 5,
      author: 'Henry',
    },
    {
      id: 402,
      boardId: 4,
      title: 'Keep Pushing',
      message: 'Never give up on your dreams.',
      gif: 'https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif',
      upvotes: 7,
      author: 'Ivy',
    },
    {
      id: 501,
      boardId: 5,
      title: 'Teamwork Rocks',
      message: 'Together we can achieve anything!',
      gif: 'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif',
      upvotes: 9,
      author: 'Jack',
    },
    {
      id: 502,
      boardId: 5,
      title: 'Awesome Job',
      message: 'Your efforts make a big difference.',
      gif: 'https://media.giphy.com/media/xUPGcl3ijl9dyxxZSw/giphy.gif',
      upvotes: 6,
      author: 'Kara',
    },
  ];
